# .gitlab-ci.yml
include:
  - local: /.ci/templates.yml
  - local: /.ci/build.yml
  - local: /.ci/test.yml
  - local: /.ci/deploy.yml
  - component: $CI_SERVER_FQDN/components/releaser/release@v0.2.2
    inputs:
      bump_versions_script_path: $CI_PROJECT_DIR/.ci/scripts/bump-versions.sh
      release_stage: release
      proposal_stage: pre
      sync_stage: sync

variables:
  INSTANCE: "Writerside/kd"
  ARTIFACT: "webHelpKD2-all.zip"
  ALGOLIA_ARTIFACT: "algolia-indexes-KD.zip"
  ALGOLIA_APP_NAME: "23BLLNEZ2S"
  ALGOLIA_INDEX_NAME: "prod_KVASIR-NEXT"
  CONFIG_JSON_PRODUCT: "kd"
  CONFIG_JSON_VERSION: "main"
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -Dstyle.color=always
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=target/
  CI_TOOLS_REGISTRY: "gitlab.ilabt.imec.be:4567/discover/ci-tools"
  WRITERSIDE_IMAGE: "${CI_TOOLS_REGISTRY}/writerside-builder:2025.04.8412"
  QUARKUS_JIB_BASE_JVM_IMAGE: "${CI_TOOLS_REGISTRY}/eclipse-temurin:21.0.7_6-jre-noble"
  JDK_IMAGE: "${CI_TOOLS_REGISTRY}/eclipse-temurin:21.0.7_6-jdk-noble"
  CI_TOOLS_IMAGE: "${CI_TOOLS_REGISTRY}:1.2.1"
  QUARKUS_JIB_PLATFORMS: "linux/amd64,linux/arm64/v8"
  QUARKUS_CONTAINER_IMAGE_PUSH: "false"
  QUARKUS_CONTAINER_IMAGE_REGISTRY: $CI_REGISTRY
  QUARKUS_CONTAINER_IMAGE_GROUP: $CI_PROJECT_PATH
  QUARKUS_CONTAINER_IMAGE_USERNAME: $CI_REGISTRY_USER
  QUARKUS_CONTAINER_IMAGE_PASSWORD: $CI_REGISTRY_PASSWORD

stages:
  - pre
  - test
  - package
  - verify
  - deploy
  - release
  - sync

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:)/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables: &commitBranchVersions
        QUARKUS_CONTAINER_IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
        QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: "$CI_COMMIT_REF_SLUG"
        QUARKUS_CONTAINER_IMAGE_PUSH: "true"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
      variables: *commitBranchVersions
