services:
  clickhouse:
    #    24.8 = LTS version
    image: altinity/clickhouse-server:24.8.14.10459.altinitystable
    ports:
      - "8123:8123"
    volumes:
      - "clickhouse_data:/var/lib/clickhouse"
      - "./plugins/clickhouse-knowledge-graph/config:/etc/clickhouse-server/users.d"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"
    environment:
      # Doubles as access key and secret key for the MinIO server
      - MINIO_ROOT_USER=kvasir
      - MINIO_ROOT_PASSWORD=kvasirkvasir

volumes:
  clickhouse_data:
    driver: local
  minio_data:
    driver: local
