services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4.13
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - 'clickhouse_data:/var/lib/clickhouse'
      - './plugins/clickhouse-knowledge-graph/initdb:/docker-entrypoint-initdb.d'
      - './plugins/clickhouse-knowledge-graph/config:/etc/clickhouse-server/users.d'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  xtdb:
    # @sha256:735f69a0a361e1e1e0ac2c1c43b76f5301ddd41808022e0bbfbcdc1b0cd4d7d2
    image: ghcr.io/xtdb/xtdb-standalone-ea
    ports:
      - "6543:3000"
    volumes:
      - "xtdb-data:/var/lib/xtdb"

volumes:
  xtdb-data:
    driver: local
  clickhouse_data:
    driver: local