kvasir:
  bootstrap:
    pods:
      - name: alice
        configuration:
          default-context:
            ex: http://example.org/
            so: http://schema.org/
          auto-ingest-rdf:  true