apiVersion: v1
kind: Namespace
metadata:
  name: kvasir
---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfga
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
