services:
  kvasir:
    # The Kvasir monolith bundles all Kvasir microservices into a single image (handy for development and testing)
    image: gitlab.ilabt.imec.be:4567/kvasir/kvasir-server/monolith:0.9.1
    volumes:
      # Load Kvasir bootstrap config (auto-creating a demo pod 'alice')
      - "./kvasir-config:/home/jboss/config"
    environment:
      - KVASIR_KG_CLICKHOUSE_HOST=localhost
      - KVASIR_KG_CLICKHOUSE_PORT=8123
      - KVASIR_SERVICES_STORAGE_S3_HOST=localhost
      - KVASIR_SERVICES_STORAGE_S3_PORT=9000
      - QUARKUS_MINIO_URL=http://localhost:9000/
      - QUARKUS_MINIO_SECURE=false
      - QUARKUS_MINIO_ACCESS_KEY=kvasir
      - QUARKUS_MINIO_SECRET_KEY=kvasirkvasir
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_SERVER_URL=http://localhost:8280
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://localhost:8280/realms/quarkus
      - QUARKUS_OIDC_CLIENT_ID=quarkus-app
      - QUARKUS_OIDC_CREDENTIALS_SECRET=secret
      - QUARKUS_OPENFGA_STORE=kvasir
      - QUARKUS_OPENFGA_URL=http://localhost:8380
    #    entrypoint: ["sleep", "3600"] # debug
    depends_on:
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/q/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  clickhouse:
    #    24.8 = lts version
    image: altinity/clickhouse-server:24.8.14.10459.altinitystable
    ports:
      - "8123:8123"
      # tcp port for clickhouse (should not be required externally)
      #- "9000:9000"
    volumes:
      - "clickhouse_data:/var/lib/clickhouse"
      - "../../plugins/clickhouse-knowledge-graph/config:/etc/clickhouse-server/users.d"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio_data:/data"
    environment:
      # Doubles as access key and secret key for the MinIO server
      - MINIO_ROOT_USER=kvasir
      - MINIO_ROOT_PASSWORD=kvasirkvasir
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092
      - --advertise-kafka-addr internal://localhost:9092
      - --mode dev-container
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.11
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    image: bitnami/keycloak:26.2.2
    depends_on:
      - postgresql
    ports:
      - "8280:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_NAME: postgres
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/realms/master/.well-known/openid-configuration",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql:
    image: postgres:17
    command: postgres -c 'max_connections=100'
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgresql:
        condition: service_healthy
    image: openfga/openfga:latest
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgresql:5432/postgres?sslmode=disable
    command: migrate

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgresql:5432/postgres?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100 #see postgres container
      - OPENFGA_PLAYGROUND_ENABLED=true
    ports:
      - "8380:8080" #http
      - "8381:8081" #grpc
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081"]
      interval: 5s
      timeout: 30s
      retries: 3

volumes:
  clickhouse_data:
    driver: local
  minio_data:
    driver: local
  postgresql_data:
    driver: local
