# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# TODO: implement monolith mode
# Launch kvasir in one of two modes: monolith or microservice
# monolith: all services are deployed in a single pod/container
# microservice: each service is deployed in its own pod/container
mode: microservice

# Global values, these are applied to all services
# Service specific values will override these globals
global:
  host: kvasir.example.com
  ingressRoutes:
    matchHost: false
    tlsEnabled: false
    proxy: "none"

  truststore: {}

  image:
    registry: gitlab.ilabt.imec.be:4567/kvasir/kvasir-server
    pullPolicy: IfNotPresent
    tag: "0.16.0"

  imagePullSecrets: []

  env:
    - name: KVASIR_BASE_URI
      value: "http://{{ .Values.global.host }}"

  applicationYaml: {}

  deploymentStrategy: {}
  #    type: RollingUpdate
  #    rollingUpdate:
  #      maxSurge: 2
  #      maxUnavailable: 1
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    httpGet:
      path: /q/health/live
      port: metrics

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    httpGet:
      path: /q/health/ready
      port: metrics

  quarkus:
    httpPort: 8080
    metricsPort: 9000

  oidc:
    enabled: true
    authServerUrl: ""
    clientId: ""
    clientSecret: ""
    realm: ""
    existingSecret: ""
    clientIdSecretKey: ""
    clientSecretSecretKey: ""
    realmSecretKey: ""

  openfga:
    url: ""

  minio:
    host: ""
    port: ""
    secure: true
    skipTlsVerify: true
    useTls: false
    access-key: ""
    secret-key: ""
    existingSecret: ""
    accessKeySecretKey: ""
    secretKeySecretKey: ""
    applicationYaml:
      kvasir:
        services:
          storage:
            s3:
              access-key: ${QUARKUS_MINIO_ACCESS_KEY}
              secret-key: ${QUARKUS_MINIO_SECRET_KEY}

  kafka:
    bootstrap-servers: ""
    applicationYaml:
      mp:
        messaging:
          outgoing:
            change_requests_publish:
              connector: smallrye-kafka
              topic: change.requests
              merge: true
              waitForWriteCompletion: false
            outbox_publish:
              connector: smallrye-kafka
              topic: outbox
              merge: true
              waitForWriteCompletion: false
            storage_events_publish:
              connector: smallrye-kafka
              topic: storage.events
              merge: true
              waitForWriteCompletion: false
            query_requests_publish:
              connector: smallrye-kafka
              topic: query.requests
              merge: true
              waitForWriteCompletion: false
            lifecycle_events_publish:
              connector: smallrye-kafka
              topic: lifecycle.events
              merge: true
              waitForWriteCompletion: false
          incoming:
            change_requests_subscribe:
              connector: smallrye-kafka
              topic: change.requests
              broadcast: true
              auto:
                offset:
                  reset: earliest
            outbox_subscribe:
              connector: smallrye-kafka
              topic: outbox
              broadcast: true
              auto:
                offset:
                  reset: earliest
            storage_events_subscribe:
              connector: smallrye-kafka
              topic: storage.events
              broadcast: true
              auto:
                offset:
                  reset: earliest
            query_requests_subscribe:
              connector: smallrye-kafka
              topic: query.requests
              broadcast: true
              auto:
                offset:
                  reset: earliest
            lifecycle_events_subscribe:
              connector: smallrye-kafka
              topic: lifecycle.events
              broadcast: true
              auto:
                offset:
                  reset: earliest
    clickhouse:
    host: ""
    port: ""
    #  username: ""
    #  password: ""
    #  database: ""
    #  existingSecret: ""
    #  usernameSecretKey: ""
    #  passwordSecretKey: ""

"init-service":
  enabled: true
  oidc:
    enabled: true
  keycloakAdmin:
    enabled: true
  clickhouse:
    enabled: true
  minio:
    enabled: true
  kafka:
    enabled: true
  openfga:
    enabled: true
  job:
    enabled: true
  applicationYaml:
    kvasir:
      bootstrap:
        exit-after-setup: true
        pods:
          - name: alice
            configuration: |
              {
                "@context": {
                  "kss": "https://kvasir.discover.ilabt.imec.be/vocab#"
                },
                "kss:autoIngestRDF": true,
                "kss:defaultContext": "{\"kss\":\"https://kvasir.discover.ilabt.imec.be/vocab#\",\"rdfs\":\"http://www.w3.org/2000/01/rdf-schema#\",\"xsd\":\"http://www.w3.org/2001/XMLSchema#\",\"schema\":\"http://schema.org/\",\"ex\":\"http://example.org/\",\"saref\":\"https://saref.etsi.org/core/\",\"mo\":\"http://purl.org/ontology/mo/\",\"dc\":\"http://purl.org/dc/elements/1.1/\",\"foaf\":\"http://xmlns.com/foaf/0.1/\",\"hasMeasurement\":{\"@reverse\":\"https://saref.etsi.org/core/measurementMadeBy\"},\"children\":{\"@reverse\":\"http://example.org/parent\"}}"
              }
            generate-clients:
              - client-id: demo-client
                client-secret: testtest
                enable-service-account: true
                openfga:
                  relationships:
                    - target-resource: "/"
                      relations: ["reader", "writer", "deleter"]
          - name: bob
            configuration: |
              {
                "@context": {
                  "kss": "https://kvasir.discover.ilabt.imec.be/vocab#"
                },
                "kss:autoIngestRDF": true,
                "kss:defaultContext": "{\"kss\":\"https://kvasir.discover.ilabt.imec.be/vocab#\",\"rdfs\":\"http://www.w3.org/2000/01/rdf-schema#\",\"xsd\":\"http://www.w3.org/2001/XMLSchema#\",\"schema\":\"http://schema.org/\",\"ex\":\"http://example.org/\",\"saref\":\"https://saref.etsi.org/core/\",\"mo\":\"http://purl.org/ontology/mo/\",\"dc\":\"http://purl.org/dc/elements/1.1/\",\"foaf\":\"http://xmlns.com/foaf/0.1/\",\"hasMeasurement\":{\"@reverse\":\"https://saref.etsi.org/core/measurementMadeBy\"},\"children\":{\"@reverse\":\"http://example.org/parent\"}}"
              }

"kg-change-processor":
  kafka:
    enabled: true
  minio:
    enabled: true
  clickhouse:
    enabled: true
  oidc:
    enabled: true

"kg-inbox-api":
  kafka:
    enabled: true
  oidc:
    enabled: true
  clickhouse:
    enabled: true
  openfga:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/changes`) && Method(`POST`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+/changes`) && Method(`POST`)"

"kg-query-api":
  kafka:
    enabled: true
  oidc:
    enabled: true
  clickhouse:
    enabled: true
  openfga:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/changes`) && Method(`GET`)"
        priority: 10
      - match: "PathRegexp(`^/[^/]+/changes`) && Method(`GET`)"
      - match: "PathRegexp(`^/[^/]+/changes/[^/]+(/records)?`) && Method(`GET`)"
      - match: "PathRegexp(`^/[^/]+/slices$`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+$`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+/changes`) && Method(`GET`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+/query`) && Method(`POST`)"
      - match: "PathRegexp(`^/[^/]+/query`) && ( Method(`POST`) || Method(`GET`) )"

"kg-stream-api":
  kafka:
    enabled: true
  oidc:
    enabled: true
  clickhouse:
    enabled: true
  openfga:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/changes`) && Header(`Accept`, `text/event-stream`)"
      - match: "PathRegexp(`^/[^/]+/life-cycle`) && Header(`Accept`, `text/event-stream`)"
      - match: "PathRegexp(`^/[^/]+/query`) && Header(`Accept`, `text/event-stream`)"
      - match: "PathRegexp(`^/[^/]+/s3`) && Header(`Accept`, `text/event-stream`)"
      - match: "Header(`Accept`, `text/event-stream`)"

"pod-management-api":
  oidc:
    enabled: true
  keycloakAdmin:
    enabled: true
  clickhouse:
    enabled: true
  minio:
    enabled: true
  kafka:
    enabled: true
  openfga:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/\\.profile`) && Method(`GET`)"
      - match: "PathRegexp(`^/([^/]+)?$`)"
      - match: "PathRegexp(`^/[^/]+/rebac/check`) && Method(`POST`)"
      - match: "PathRegexp(`^/[^/]+/rebac/relationships`) && ( Method(`GET`) || Method(`POST`) )"

"simple-rdf-ingester":
  oidc:
    enabled: true
  minio:
    enabled: true
  kafka:
    enabled: true
  clickhouse:
    enabled: true

"storage-api":
  minio:
    enabled: true
  oidc:
    enabled: true
  kafka:
    enabled: true
  clickhouse:
    enabled: true
  openfga:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/s3/[^/]+`)"
      - match: "PathRegexp(`^/[^/]+/s3`)"

"ui-service":
  kafka:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: PathPrefix(`/_ui`)
        priority: 99999
