# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# TODO: implement monolith mode
# Launch kvasir in one of two modes: monolith or microservice
# monolith: all services are deployed in a single pod/container
# microservice: each service is deployed in its own pod/container
mode: microservice

# Global values, these are applied to all services
# Service specific values will override these globals
global:
  host: kvasir.example.com
  ingressRoutes:
    matchHost: false
    tlsEnabled: false
    proxy: "none"

  truststore: {}

  image:
    registry: gitlab.ilabt.imec.be:4567/kvasir/kvasir-server
    pullPolicy: IfNotPresent
    tag: "0.4.0"

  imagePullSecrets: []

  env:
    - name: KVASIR_BASE_URI
      value: "http://{{ .Values.global.host }}"

  applicationYaml: {}

  deploymentStrategy: {}
  #    type: RollingUpdate
  #    rollingUpdate:
  #      maxSurge: 2
  #      maxUnavailable: 1
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    httpGet:
      path: /q/health/live
      port: metrics

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    httpGet:
      path: /q/health/ready
      port: metrics

  quarkus:
    httpPort: 8080
    metricsPort: 9000

  oidc:
    enabled: true
    authServerUrl: ""
    clientId: ""
    clientSecret: ""
    realm: ""
    existingSecret: ""
    clientIdSecretKey: ""
    clientSecretSecretKey: ""
    realmSecretKey: ""

  minio:
    host: ""
    port: ""
    secure: true
    skipTlsVerify: true
    useTls: false
    access-key: ""
    secret-key: ""
    existingSecret: ""
    accessKeySecretKey: ""
    secretKeySecretKey: ""
    applicationYaml:
      kvasir:
        services:
          storage:
            s3:
              access-key: ${QUARKUS_MINIO_ACCESS_KEY}
              secret-key: ${QUARKUS_MINIO_SECRET_KEY}

  kafka:
    bootstrap-servers: ""
    applicationYaml:
      mp:
        messaging:
          outgoing:
            change_requests_publish:
              connector: smallrye-kafka
              topic: change.requests
              merge: true
              waitForWriteCompletion: false
            outbox_publish:
              connector: smallrye-kafka
              topic: outbox
              merge: true
              waitForWriteCompletion: false
            storage_events_publish:
              connector: smallrye-kafka
              topic: storage.events
              merge: true
              waitForWriteCompletion: false
            query_requests_publish:
              connector: smallrye-kafka
              topic: query.requests
              merge: true
              waitForWriteCompletion: false
            lifecycle_events_publish:
              connector: smallrye-kafka
              topic: lifecycle.events
              merge: true
              waitForWriteCompletion: false
          incoming:
            change_requests_subscribe:
              connector: smallrye-kafka
              topic: change.requests
              broadcast: true
              auto:
                offset:
                  reset: earliest
            outbox_subscribe:
              connector: smallrye-kafka
              topic: outbox
              broadcast: true
              auto:
                offset:
                  reset: earliest
            storage_events_subscribe:
              connector: smallrye-kafka
              topic: storage.events
              broadcast: true
              auto:
                offset:
                  reset: earliest
            query_requests_subscribe:
              connector: smallrye-kafka
              topic: query.requests
              broadcast: true
              auto:
                offset:
                  reset: earliest
            lifecycle_events_subscribe:
              connector: smallrye-kafka
              topic: lifecycle.events
              broadcast: true
              auto:
                offset:
                  reset: earliest
    clickhouse:
    host: ""
    port: ""
  #  username: ""
  #  password: ""
  #  database: ""
  #  existingSecret: ""
  #  usernameSecretKey: ""
  #  passwordSecretKey: ""

#      - KVASIR_KG_CLICKHOUSE_HOST=localhost
#      - KVASIR_KG_CLICKHOUSE_PORT=8123
#      - KVASIR_SERVICES_STORAGE_S3_HOST=localhost
#      - KVASIR_SERVICES_STORAGE_S3_PORT=9000
#      - QUARKUS_MINIO_URL=http://localhost:9000/
#      - QUARKUS_MINIO_SECURE=true
#      - QUARKUS_MINIO_ACCESS_KEY=kvasir
#      - QUARKUS_MINIO_SECRET_KEY=kvasirkvasir
#      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
#      - QUARKUS_OIDC_AUTH_SERVER_URL=http://localhost:8280/realms/quarkus
#      - QUARKUS_OIDC_CLIENT_ID=quarkus-app
#      - QUARKUS_OIDC_CREDENTIALS_SECRET=secret

"init-service":
  config: {}
  oidc:
    enabled: true
    keycloakAdmin:
      enabled: true
  clickhouse:
    enabled: true
  minio:
    enabled: true
  kafka:
    enabled: true
  applicationYaml:
    kvasir:
      bootstrap:
        pods:
          - name: alice
            default-context: |
              {
                "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
                "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                "xsd": "http://www.w3.org/2001/XMLSchema#",
                "schema": "http://schema.org/",
                "ex": "http://example.org/",
                "saref": "https://saref.etsi.org/core/",
                "hasMeasurement": {
                  "@reverse": "https://saref.etsi.org/core/measurementMadeBy"
                },
                "children": { "@reverse": "http://example.org/parent" }
              }
            auto-ingest-rdf: true
          - name: bob
            default-context: |
              {
                "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
                "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                "xsd": "http://www.w3.org/2001/XMLSchema#",
                "schema": "http://schema.org/",
                "ex": "http://example.org/"
              }
            auto-ingest-rdf: false
          - name: swdemo
            default-context: |
              {
                "@language": "en",
                "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
                "voc": "https://swapi.co/vocabulary/",
                "commons": "https://commons.wikimedia.org/wiki/Special:FilePath/",
                "dc": "http://purl.org/dc/elements/1.1/",
                "dct": "http://purl.org/dc/terms/",
                "owl": "http://www.w3.org/2002/07/owl#",
                "p": "http://www.wikidata.org/prop/",
                "pq": "http://www.wikidata.org/prop/qualifier/",
                "ps": "http://www.wikidata.org/prop/statement/",
                "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                "wd": "http://www.wikidata.org/entity/",
                "wds": "http://www.wikidata.org/entity/statement/",
                "wdt": "http://www.wikidata.org/prop/direct/",
                "wgs": "http://www.w3.org/2003/01/geo/wgs84_pos#",
                "wikibase": "http://wikiba.se/ontology#",
                "xml": "http://www.w3.org/XML/1998/namespace",
                "xsd": "http://www.w3.org/2001/XMLSchema#"
              }
            auto-ingest-rdf: true

"kg-change-processor":
  kafka:
    enabled: true
  minio:
    enabled: true
  clickhouse:
    enabled: true
  oidc:
    enabled: true

"kg-inbox-api":
  kafka:
    enabled: true
  oidc:
    enabled: true
  clickhouse:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/changes`) && Method(`POST`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+/changes`) && Method(`POST`)"

"kg-query-api":
  kafka:
    enabled: true
  oidc:
    enabled: true
  clickhouse:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/changes`) && Method(`GET`)"
        priority: 10
      - match: "PathRegexp(`^/[^/]+/changes`) && Method(`GET`)"
      - match: "PathRegexp(`^/[^/]+/changes/[^/]+(/records)?`) && Method(`GET`)"
      - match: "PathRegexp(`^/[^/]+/slices$`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+$`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+/changes`) && Method(`GET`)"
      - match: "PathRegexp(`^/[^/]+/slices/[^/]+/query`) && Method(`POST`)"
      - match: "PathRegexp(`^/[^/]+/query`) && Method(`POST`)"

"kg-stream-api":
  kafka:
    enabled: true
  oidc:
    enabled: true
  clickhouse:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/changes`) && Header(`Accept`, `text/event-stream`)"
      - match: "PathRegexp(`^/[^/]+/life-cycle-events`) && Header(`Accept`, `text/event-stream`)"
      - match: "PathRegexp(`^/[^/]+/query-events`) && Header(`Accept`, `text/event-stream`)"
      - match: "PathRegexp(`^/[^/]+/s3-events`) && Header(`Accept`, `text/event-stream`)"
      - match: "Header('Accept', 'text/event-stream"

"pod-management-api":
  oidc:
    enabled: true
    keycloakAdmin:
      enabled: true
  clickhouse:
    enabled: true
  minio:
    enabled: true
  kafka:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/\\.profile`) && Method(`GET`)"
      - match: "PathRegexp(`^/([^/]+)?$`)"

"simple-rdf-ingester":
  oidc:
    enabled: true
  minio:
    enabled: true
  kafka:
    enabled: true
  clickhouse:
    enabled: true

"storage-api":
  minio:
    enabled: true
  oidc:
    enabled: true
  kafka:
    enabled: true
  clickhouse:
    enabled: true
  ingressRoutes:
    enabled: true
    routes:
      - match: "PathRegexp(`^/[^/]+/s3/[^/]+`)"
      - match: "PathRegexp(`^/[^/]+/s3`)"
