build:maven:
  extends:
    - .ignore-tags
    - .maven-cache
    - .docker-in-docker
    - .branch-only
  stage: test
  image: $CI_TOOLS_IMAGE
  tags: ["cache", "docker"]
  variables:
    KVASIR_KG_CLICKHOUSE_HOST: docker
    KVASIR_MESSAGING_KAFKA_BOOTSTRAP_SERVERS: docker:9092
    KVASIR_MESSAGING_KAFKA_ADVERTISED_HOSTNAME: docker
    KVASIR_STORAGE_S3_ENDPOINT: http://docker:9000
    KVASIR_AUTH_KEYCLOAK_URL: http://docker:8280
    KVASIR_PEP_OPENFGA_URL: http://docker:8380
    KAFKA_BOOTSTRAP_SERVERS: docker:9092
    KAFKA_ADVERTISED_HOSTNAME: docker
  script:
    - set -xe
    - docker compose -f compose/compose.devservices.yml up --wait --quiet-pull --no-color
    - ./mvnw $MAVEN_CLI_OPTS test -Pservices -Dcompose.skip=true -Dmodel-tx.skip=true
  interruptible: true
  after_script:
    - awk -F, '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered (line coverage)" }' target/coverage/jacoco.csv
    - docker compose -f compose/compose.devservices.yml logs > compose-logs.txt
    - docker compose -f compose/compose.devservices.yml down --volumes --remove-orphans
  coverage: "/(d+.d+) % covered/"
  artifacts:
    paths:
      - compose-logs.txt
      - "**/target"
    reports:
      coverage_report:
        coverage_format: jacoco
        path: target/coverage/jacoco.xml
      junit: "**/TEST-*.xml"
    when: always

package:maven:
  extends:
    - .ignore-tags
    - .maven-cache
    - .docker-in-docker
    - .branch-only
  stage: package
  needs: ["build:maven"]
  image: $JDK_IMAGE
  tags: ["cache", "docker"]
  script:
    - ./mvnw $MAVEN_CLI_OPTS -DskipTests package -Pservices -Dcompose.skip=true -Dmodel-tx.skip=true
      -Dquarkus.container-image.push=$QUARKUS_CONTAINER_IMAGE_PUSH
      -Dquarkus.container-image.tag=${IMAGE_TAG}
      -Dquarkus.container-image.additional-tags=${IMAGE_ADDITIONAL_TAG}
  interruptible: true
  artifacts:
    paths:
      - "services/monolith/target/openapi"

build:openapi:
  extends:
    - .ignore-tags
    - .maven-cache
    - .main-branch-only
  image:
    name: ${CI_TOOLS_REGISTRY}/redocly/cli:2.13.0
    entrypoint: [""]
  stage: package
  needs:
    - package:maven
  script:
    - mkdir _openapi
    - redocly build-docs -o ./_openapi/index.html ./services/monolith/target/openapi/openapi.yaml --theme.openapi.pathInMiddlePanel=true
  artifacts:
    paths:
      - _openapi
    expire_in: 1 week

build:writerside:
  extends:
    - .ignore-tags
    - .branch-only
  stage: test
  image: $WRITERSIDE_IMAGE
  script:
    - set -xe
    - export DISPLAY=:99
    - Xvfb :99 &
    - /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $INSTANCE --runner gitlab -output-dir public/
    - echo "Checking for build errors..."
    - curl -o public/wrs-checker.jar -L https://packages.jetbrains.team/maven/p/writerside/maven/com/jetbrains/writerside/writerside-ci-checker/1.0/writerside-ci-checker-1.0.jar
    - /opt/builder/jbr/bin/java -jar public/wrs-checker.jar public/report.json $INSTANCE
  artifacts:
    paths:
      - public/$ARTIFACT
      - public/report.json
      - public/$ALGOLIA_ARTIFACT
    expire_in: 1 week
  interruptible: true
