# Import using openfga/cli
# fga store import --file dependencies/openfga/obelisk.fga.yaml

name: obelisk
model: |+
  model
    schema 1.1
  
  type user
  
  type platform
    relations
      define can_create_namespace: manager or namespace_creator
      define can_manage: manager
      define manager: [user]
      define namespace_creator: [user, user:*]
  
  type namespace
    relations
      define blocked: [user]
      define can_contribute: (can_manage or contributor or can_contribute from parent) but not blocked
      define can_manage: (manager or can_manage from parent) but not blocked
      define can_view: (can_contribute or viewer or can_view from parent) but not blocked
      define contributor: [user]
      define direct_member: viewer or contributor or manager
      define manager: [user]
      define parent: [namespace, platform]
      define viewer: [user, user:*]
  
  type dataset
    relations
      define blocked: [user]
      define can_contribute: (can_manage or contributor or can_contribute from namespace) but not blocked
      define can_manage: (manager or can_manage from namespace) but not blocked
      define can_view: (can_contribute or viewer or can_view from namespace) but not blocked
      define contributor: [user]
      define direct_member: viewer or contributor or manager
      define manager: [user]
      define namespace: [namespace]
      define viewer: [user, user:*]
