<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>kvasir-libs</groupId>
        <artifactId>libs-parent</artifactId>
        <version>0.9.2</version>
    </parent>

    <artifactId>test-utils</artifactId>

    <dependencies>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>utils</artifactId>
            <version>0.9.2</version>
        </dependency>
        <dependency>
            <groupId>org.ajbrown</groupId>
            <artifactId>name-machine</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>kotlin-extensions</artifactId>
        </dependency>
    </dependencies>

</project>