<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>kvasir-services</groupId>
    <artifactId>services-parent</artifactId>
    <version>0.10.0</version>

    <packaging>pom</packaging>

    <parent>
        <artifactId>kvasir-parent</artifactId>
        <groupId>kvasir</groupId>
        <version>0.10.0</version>
    </parent>

    <properties>
        <quarkus.jib.jvm-additional-arguments>-Djava.net.preferIPv4Stack=true</quarkus.jib.jvm-additional-arguments>
    </properties>

    <modules>
        <module>kg-change-processor</module>
        <module>kg-inbox-api</module>
        <module>kg-query-api</module>
        <module>kg-stream-api</module>
        <module>monolith</module>
        <module>pod-management-api</module>
        <module>simple-rdf-ingester</module>
        <module>storage-api</module>
        <module>init-service</module>
        <module>ui-service</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.google.cloud.tools/jib-core -->
        <dependency>
            <groupId>com.google.cloud.tools</groupId>
            <artifactId>jib-core</artifactId>
            <version>0.27.0</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.smallrye</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>openfga</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>${quarkus.platform.group-id}</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <kvasir.plugins.policy-agent.openfga.enabled>true</kvasir.plugins.policy-agent.openfga.enabled>
            </properties>
        </profile>
        <profile>
            <id>a4ds</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>${quarkus.platform.group-id}</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
            <properties>
              <kvasir.plugins.policy-agent.uma.enabled>true</kvasir.plugins.policy-agent.uma.enabled>
            </properties>
        </profile>
        <profile>
            <id>noauth</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>${quarkus.platform.group-id}</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.container-image.name>${quarkus.application.name:unset}</quarkus.container-image.name>
            </properties>
        </profile>
    </profiles>
</project>
