quarkus.kafka-streams.topics=changes.incoming,changes.processing-completed
%dev.quarkus.kafka-streams.application-id=${quarkus.uuid}
%test.quarkus.kafka-streams.application-id=${quarkus.uuid}
%test.kvasir-ext.change-processor.shutdown-on-error=false
%test.kvasir-ext.change-processor.ignore-non-existing-pod=true
%dev.kvasir-ext.change-processor.shutdown-on-error=false
%dev.kvasir-ext.change-processor.ignore-non-existing-pod=true