%test.kvasir.change-processor.shutdown-on-error=false
%test.kvasir.change-processor.ignore-non-existing-pod=true

%dev.kvasir.change-processor.shutdown-on-error=false
%dev.kvasir.change-processor.ignore-non-existing-pod=true