<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>clickhouse-knowledge-graph</artifactId>
    <version>0.11.0</version>

    <parent>
        <groupId>kvasir-plugins</groupId>
        <artifactId>plugins-parent</artifactId>
        <version>0.11.0</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>utils</artifactId>
            <version>0.11.0</version>
        </dependency>
        <dependency>
            <groupId>kvasir-plugins</groupId>
            <artifactId>default-knowledge-graph</artifactId>
            <version>0.11.0</version>
        </dependency>
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-mutiny-vertx-web-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.qute.web</groupId>
            <artifactId>quarkus-qute-web</artifactId>
        </dependency>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>test-utils</artifactId>
            <version>0.11.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>clickhouse-test-utils</artifactId>
            <version>0.11.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>