services:
  kvasir:
    # The Kvasir monolith bundles all Kvasir microservices into a single image (handy for development and testing)
    image: gitlab.ilabt.imec.be:4567/kvasir/kvasir-server/monolith:0.12.0
    volumes:
      # Load Kvasir bootstrap config (auto-creating a demo pod 'alice')
      - "./kvasir-config:/home/jboss/config${SELINUX_MOUNT_FLAG}"
    environment:
      - KVASIR_KG_CLICKHOUSE_HOST=localhost
      - KVASIR_KG_CLICKHOUSE_PORT=8123
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - QUARKUS_S3_ENDPOINT_OVERRIDE=http://localhost:9000
      - QUARKUS_S3_AWS_REGION=us-east-1
      - QUARKUS_S3_AWS_CREDENTIALS_TYPE=static
      - QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID=kvasir
      - QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY=kvasirkvasir
      - QUARKUS_S3_PATH_STYLE_ACCESS=true
      - QUARKUS_KEYCLOAK_ADMIN_CLIENT_SERVER_URL=http://localhost:8280
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://localhost:8280/realms/quarkus
      - QUARKUS_OIDC_CLIENT_ID=quarkus-app
      - QUARKUS_OIDC_CREDENTIALS_SECRET=secret
      - QUARKUS_OPENFGA_STORE=kvasir
      - QUARKUS_OPENFGA_URL=http://localhost:8380
    #    entrypoint: ["sleep", "3600"] # debug
    depends_on:
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/q/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
