<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>kvasir-services</groupId>
        <artifactId>api-services-parent</artifactId>
        <version>0.11.1</version>
        <relativePath>../api-services/pom.xml</relativePath>
    </parent>

    <artifactId>init-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>utils</artifactId>
            <version>0.11.1</version>
        </dependency>
        <dependency>
            <groupId>kvasir-plugins</groupId>
            <artifactId>clickhouse-knowledge-graph</artifactId>
            <version>0.11.1</version>
        </dependency>
        
    </dependencies>

</project>
