# helm repo add clickhouse-operator https://docs.altinity.com/clickhouse-operator/
# helm install clickhouse-operator clickhouse-operator/altinity-clickhouse-operator \
#  --namespace operators --create-namespace -f clickhouse/operator/values.yaml.gotmpl

configs:
  files:
    config.yaml:
      watch:
        namespaces:
          - clickhouse