apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: clickhouse
data:
  default-user.xml: |
    <clickhouse>
      <users>
        <default>
        </default>
      </users>
    </clickhouse>
  kvasir.config.xml: |
    <clickhouse>
        <profiles>
            <default>
                <allow_experimental_dynamic_type>1</allow_experimental_dynamic_type>
            </default>
        </profiles>
    </clickhouse>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: altinity/clickhouse-server:24.8.14.10459.altinitystable
          env:
            - name: CLICKHOUSE_LOG_TO_CONSOLE
              value: "1"
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /etc/clickhouse-server/users.d/default-user.xml
              subPath: default-user.xml
            - name: config
              mountPath: /etc/clickhouse-server/users.d/kvasir.config.xml
              subPath: kvasir.config.xml
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: clickhouse-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - port: 8123
      targetPort: 8123
