<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>kvasir-plugins</groupId>
        <artifactId>plugins-parent</artifactId>
        <version>0.9.2</version>
    </parent>

    <artifactId>openfga-policy-agent</artifactId>

    <dependencies>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>definitions</artifactId>
            <version>0.9.2</version>
        </dependency>
        <dependency>
            <groupId>kvasir-libs</groupId>
            <artifactId>utils</artifactId>
            <version>0.9.2</version>
        </dependency>
        <dependency>
            <groupId>kvasir-plugins</groupId>
            <artifactId>common-http-extensions</artifactId>
            <version>0.9.2</version>
        </dependency>
        <dependency>
            <groupId>idlab.quarkus.ext.pep.openfga</groupId>
            <artifactId>openfga-pep</artifactId>
            <version>${idlab.extension.openfga.version}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-keycloak-admin-rest-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-security</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>kotlin-extensions</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>