quarkus:
  http:
    cors:
      enabled: true
      origins: /.*/
      access-control-allow-credentials: true
      exposed-headers:
        - Accept-Patch
        - Accept-Post
        - Accept-Put
        - Allow
        - ETag
        - Last-Modified
        - Link
        - Location
        - WAC-Allow
        - Www-Authenticate
  smallrye-openapi:
    store-schema-directory: target/openapi

"%dev":
  quarkus:
    http:
      host: 0.0.0.0
      access-log:
        enabled: false
  kvasir:
    bootstrap:
      pods:
        - name: alice
          configuration:
            default-context:
              ex: http://example.org/
              so: http://schema.org/
            auto-ingest-rdf: true