kvasir:
  plugins:
    policy-agent:
      openfga:
        enabled: true
  services:
    storage:
      s3:
        host: ${quarkus.minio.url}
        port: ${quarkus.minio.port}
        access-key: ${quarkus.minio.access-key}
        secret-key: ${quarkus.minio.secret-key}
quarkus:
  http:
    cors:
      enabled: true
      origins: /.*/
      exposed-headers: Link, Location
  minio:
    devservices:
  smallrye-openapi:
    store-schema-directory: target/openapi

"%dev":
  quarkus:
    http:
      access-log:
        enabled: true
      cors:
        enabled: true
        origins: http://localhost:3000,http://localhost:4200, http://localhost:5173
    minio:
      url: localhost
      port: 9000
      secure: false
      access-key: kvasir
      secret-key: kvasirkvasir
  kvasir:
    plugins:
      policy-agent:
        keycloak:
          realm-initializer:
            request-password-reset: false
    webclient-uri: http://localhost:8080/_ui
    bootstrap:
      pods:
        - name: alice
          configuration: |
            {
              "@context": {
                "kss": "https://kvasir.discover.ilabt.imec.be/vocab#"
              },
              "kss:autoIngestRDF": true,
              "kss:defaultContext": "{\"kss\":\"https://kvasir.discover.ilabt.imec.be/vocab#\",\"rdfs\":\"http://www.w3.org/2000/01/rdf-schema#\",\"xsd\":\"http://www.w3.org/2001/XMLSchema#\",\"schema\":\"http://schema.org/\",\"ex\":\"http://example.org/\",\"saref\":\"https://saref.etsi.org/core/\",\"mo\":\"http://purl.org/ontology/mo/\",\"dc\":\"http://purl.org/dc/elements/1.1/\",\"foaf\":\"http://xmlns.com/foaf/0.1/\",\"hasMeasurement\":{\"@reverse\":\"https://saref.etsi.org/core/measurementMadeBy\"},\"children\":{\"@reverse\":\"http://example.org/parent\"}}"
            }
          generate-clients:
            - client-id: demo-client
              client-secret: testtest
              enable-service-account: true
              openfga:
                relationships:
                  - target-resource: "/"
                    relations: [ "reader", "writer", "deleter" ]
        - name: bob
          configuration: |
            {
              "@context": {
                "kss": "https://kvasir.discover.ilabt.imec.be/vocab#"
              },
              "kss:autoIngestRDF": true,
              "kss:defaultContext": "{\"kss\":\"https://kvasir.discover.ilabt.imec.be/vocab#\",\"rdfs\":\"http://www.w3.org/2000/01/rdf-schema#\",\"xsd\":\"http://www.w3.org/2001/XMLSchema#\",\"schema\":\"http://schema.org/\",\"ex\":\"http://example.org/\",\"saref\":\"https://saref.etsi.org/core/\",\"mo\":\"http://purl.org/ontology/mo/\",\"dc\":\"http://purl.org/dc/elements/1.1/\",\"foaf\":\"http://xmlns.com/foaf/0.1/\",\"hasMeasurement\":{\"@reverse\":\"https://saref.etsi.org/core/measurementMadeBy\"},\"children\":{\"@reverse\":\"http://example.org/parent\"}}"
            }