kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "pgauth"
  namespace: "auth"
  labels:
    team: kvasir

spec:
  teamId: "kvasir"
  postgresql:
    version: "17"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    keycloak: ["SUPERUSER"]
    openfga: ["SUPERUSER"]
  databases:
    keycloak: keycloak
    openfga: openfga

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
