<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>kvasir-services</groupId>
        <artifactId>services-parent</artifactId>
        <version>${revision}</version>
        <relativePath>..</relativePath>
    </parent>
    <artifactId>api-services-parent</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>../kg-changes-api</module>
        <module>../kg-query-api</module>
        <module>../kg-stream-api</module>
        <module>../pod-management-api</module>
        <module>../storage-api</module>
        <module>../init-service</module>
        <module>../monolith</module>
        <module>../solid-api</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>kvasir-plugins</groupId>
            <artifactId>openfga-pep</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
